@extends('layouts.app')
@section('content')
    <header class="content-header"><div><p class="eyebrow">Finance / Costing</p><h1>{{ $entry ? 'Edit' : 'New' }} cost entry</h1></div></header>
    <form method="POST" action="{{ $entry ? route('finance.cost-entries.update',$entry) : route('finance.cost-entries.store') }}">@csrf @if($entry) @method('PUT') @endif
        <label>Organization<select name="organization_id" required>@foreach($organizations as $organization)<option value="{{ $organization->id }}" @selected(old('organization_id',$entry?->organization_id)==$organization->id)>{{ $organization->name }}</option>@endforeach</select></label>
        <label>Farm<select name="farm_id"><option value="">No farm</option>@foreach($farms as $farm)<option value="{{ $farm->id }}" @selected(old('farm_id',$entry?->farm_id)==$farm->id)>{{ $farm->name }}</option>@endforeach</select></label>
        <label>Date<input type="date" name="entry_date" value="{{ old('entry_date',$entry?->entry_date?->toDateString() ?? now()->toDateString()) }}" required></label><label>Title<input name="title" value="{{ old('title',$entry?->title) }}" required></label>
        <label>Category<select name="cost_category_id" required>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('cost_category_id',$entry?->cost_category_id)==$category->id)>{{ $category->name }}</option>@endforeach</select></label>
        <label>Cost centre<select name="cost_centre_id"><option value="">None</option>@foreach($centres as $centre)<option value="{{ $centre->id }}" @selected(old('cost_centre_id',$entry?->cost_centre_id)==$centre->id)>{{ $centre->name }}</option>@endforeach</select></label>
        <label>Source<select name="source_module">@foreach(['manual','labour','task','inventory','crop','livestock','irrigation','asset','maintenance','other'] as $source)<option value="{{ $source }}" @selected(old('source_module',$entry?->source_module ?? 'manual')===$source)>{{ $source }}</option>@endforeach</select></label>
        <label>Reference label<input name="reference_label" value="{{ old('reference_label',$entry?->reference_label) }}"></label><label>Quantity<input type="number" step="0.0001" name="quantity" value="{{ old('quantity',$entry?->quantity) }}"></label><label>Unit<input name="unit" value="{{ old('unit',$entry?->unit) }}"></label><label>Unit cost<input type="number" step="0.0001" name="unit_cost" value="{{ old('unit_cost',$entry?->unit_cost) }}"></label><label>Amount<input type="number" step="0.01" name="amount" value="{{ old('amount',$entry?->amount) }}" required></label><label>Currency<input name="currency" maxlength="3" value="{{ old('currency',$entry?->currency ?? 'KES') }}"></label>
        <h2>Allocation</h2><label>Allocation type<select name="allocation_type">@foreach(['general_farm','field','crop_cycle','crop_activity','livestock_animal','livestock_group','livestock_event','irrigation_event','asset','maintenance_record','work_order','task','inventory_movement','worker','team','other'] as $type)<option value="{{ $type }}" @selected(old('allocation_type',$entry?->allocations->first()?->allocation_type ?? 'general_farm')===$type)>{{ $type }}</option>@endforeach</select></label><label>Allocation label<input name="allocation_label" value="{{ old('allocation_label',$entry?->allocations->first()?->allocation_label) }}"></label><label>Allocation amount<input type="number" step="0.01" name="allocation_amount" value="{{ old('allocation_amount',$entry?->allocations->first()?->amount ?? $entry?->amount) }}"></label>
        <label>Notes<textarea name="notes">{{ old('notes',$entry?->notes) }}</textarea></label>@include('finance::partials.errors')<button class="button" type="submit">Save cost entry</button>
    </form>
@endsection
