@extends('layouts.app')
@section('content')
    <header class="content-header"><div><p class="eyebrow">Crop cycle</p><h1>{{ $cycle ? 'Edit cycle' : 'New cycle' }}</h1></div><a class="button secondary" href="{{ route('crops.cycles.index') }}">Back</a></header>
    <form class="form-panel" method="POST" action="{{ $cycle ? route('crops.cycles.update',$cycle) : route('crops.cycles.store') }}">@csrf @if($cycle) @method('PUT') @endif
        <div class="field-group"><label for="organization_id">Organization</label><select id="organization_id" name="organization_id" required>@foreach($organizations as $organization)<option value="{{ $organization->id }}" @selected((string)old('organization_id',$cycle?->organization_id)===(string)$organization->id)>{{ $organization->name }}</option>@endforeach</select></div>
        <div class="field-group"><label for="farm_id">Farm</label><select id="farm_id" name="farm_id" required>@foreach($farms as $farm)<option value="{{ $farm->id }}" @selected((string)old('farm_id',$cycle?->farm_id)===(string)$farm->id)>{{ $farm->name }}</option>@endforeach</select></div>
        <div class="field-group"><label for="field_id">Field</label><select id="field_id" name="field_id" required>@foreach($fields as $field)<option value="{{ $field->id }}" @selected((string)old('field_id',$cycle?->field_id)===(string)$field->id)>{{ $field->name }} ({{ $field->farm->name }})</option>@endforeach</select>@error('field_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="crop_id">Crop</label><select id="crop_id" name="crop_id" required>@foreach($crops as $crop)<option value="{{ $crop->id }}" @selected((string)old('crop_id',$cycle?->crop_id)===(string)$crop->id)>{{ $crop->name }}</option>@endforeach</select></div>
        <div class="field-group"><label for="variety_id">Variety</label><select id="variety_id" name="variety_id"><option value="">No variety</option>@foreach($varieties as $variety)<option value="{{ $variety->id }}" @selected((string)old('variety_id',$cycle?->variety_id)===(string)$variety->id)>{{ $variety->name }} ({{ $variety->crop->name }})</option>@endforeach</select>@error('variety_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="season_id">Season</label><select id="season_id" name="season_id"><option value="">No season</option>@foreach($seasons as $season)<option value="{{ $season->id }}" @selected((string)old('season_id',$cycle?->season_id)===(string)$season->id)>{{ $season->name }}</option>@endforeach</select></div>
        <div class="field-group"><label for="name">Name</label><input id="name" name="name" value="{{ old('name',$cycle?->name) }}" required></div>
        @foreach(['planned_start_date'=>'Planned start','actual_planting_date'=>'Actual planting','expected_harvest_date'=>'Expected harvest'] as $field=>$label)<div class="field-group"><label for="{{ $field }}">{{ $label }}</label><input id="{{ $field }}" name="{{ $field }}" type="date" value="{{ old($field,$cycle?->$field?->format('Y-m-d')) }}"></div>@endforeach
        @foreach(['area_planted'=>'Area planted','plant_population'=>'Plant population'] as $field=>$label)<div class="field-group"><label for="{{ $field }}">{{ $label }}</label><input id="{{ $field }}" name="{{ $field }}" type="number" min="0" step="0.01" value="{{ old($field,$cycle?->$field) }}"></div>@endforeach
        @foreach(['area_unit'=>'Area unit','spacing'=>'Spacing','seed_source'=>'Seed source'] as $field=>$label)<div class="field-group"><label for="{{ $field }}">{{ $label }}</label><input id="{{ $field }}" name="{{ $field }}" value="{{ old($field,$cycle?->$field) }}"></div>@endforeach
        <div class="field-group"><label for="manager_user_id">Manager</label><select id="manager_user_id" name="manager_user_id"><option value="">No manager</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected((string)old('manager_user_id',$cycle?->manager_user_id)===(string)$user->id)>{{ $user->name }}</option>@endforeach</select></div>
        <div class="field-group"><label for="status">Status</label><select id="status" name="status">@foreach(['planned','planted','growing','harvesting','closed','cancelled'] as $status)<option value="{{ $status }}" @selected(old('status',$cycle?->status ?? 'planned')===$status)>{{ ucfirst($status) }}</option>@endforeach</select></div>
        <button type="submit">Save cycle</button>
    </form>
@endsection
