@extends('layouts.app')
@section('content')
    <header class="content-header"><div><p class="eyebrow">Maintenance record</p><h1>Record maintenance</h1></div><a class="button secondary" href="{{ route('assets.maintenance-records.index') }}">Back</a></header>
    <form class="form-panel" method="POST" action="{{ route('assets.maintenance-records.store') }}">@csrf
        @include('assets::partials.scope-fields', ['record' => null])
        <div class="field-group"><label for="asset_id">Asset</label><select id="asset_id" name="asset_id" required>@foreach($assets as $asset)<option value="{{ $asset->id }}" @selected(old('asset_id')==$asset->id)>{{ $asset->asset_code }} - {{ $asset->name }}</option>@endforeach</select>@error('asset_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="maintenance_schedule_id">Schedule</label><select id="maintenance_schedule_id" name="maintenance_schedule_id"><option value="">None</option>@foreach($schedules as $schedule)<option value="{{ $schedule->id }}" @selected(old('maintenance_schedule_id')==$schedule->id)>{{ $schedule->schedule_number }}</option>@endforeach</select>@error('maintenance_schedule_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="maintenance_type">Type</label><select id="maintenance_type" name="maintenance_type">@foreach(['routine_service','inspection','repair','calibration','cleaning','lubrication','replacement','safety_check','other'] as $value)<option value="{{ $value }}" @selected(old('maintenance_type','routine_service')===$value)>{{ ucfirst(str_replace('_',' ',$value)) }}</option>@endforeach</select></div>
        <div class="field-group"><label for="maintenance_date">Date</label><input id="maintenance_date" name="maintenance_date" type="date" value="{{ old('maintenance_date', today()->toDateString()) }}" required></div>
        <div class="field-group"><label for="status">Status</label><select id="status" name="status">@foreach(['recorded','approved','cancelled'] as $value)<option value="{{ $value }}" @selected(old('status','recorded')===$value)>{{ ucfirst($value) }}</option>@endforeach</select></div>
        @foreach(['related_task_id'=>$tasks,'performed_by_worker_id'=>$workers,'team_id'=>$teams,'product_id'=>$products] as $field=>$items)<div class="field-group"><label for="{{ $field }}">{{ ucfirst(str_replace('_id','',str_replace('_',' ',$field))) }}</label><select id="{{ $field }}" name="{{ $field }}"><option value="">None</option>@foreach($items as $item)<option value="{{ $item->id }}" @selected(old($field)==$item->id)>{{ $item->name ?? $item->task_number }}</option>@endforeach</select>@error($field)<span class="error">{{ $message }}</span>@enderror</div>@endforeach
        <div class="field-group"><label for="performed_by_user_id">Performed by user</label><select id="performed_by_user_id" name="performed_by_user_id"><option value="">None</option>@foreach($memberships as $membership)<option value="{{ $membership->user_id }}" @selected(old('performed_by_user_id')==$membership->user_id)>{{ $membership->user?->name }}</option>@endforeach</select>@error('performed_by_user_id')<span class="error">{{ $message }}</span>@enderror</div>
        @foreach(['service_provider'=>'Service provider','quantity_unit'=>'Quantity unit','currency'=>'Currency'] as $field=>$label)<div class="field-group"><label for="{{ $field }}">{{ $label }}</label><input id="{{ $field }}" name="{{ $field }}" value="{{ old($field) }}"></div>@endforeach
        @foreach(['quantity_used'=>'Quantity used','external_cost'=>'External cost'] as $field=>$label)<div class="field-group"><label for="{{ $field }}">{{ $label }}</label><input id="{{ $field }}" name="{{ $field }}" type="number" step="0.01" min="0" value="{{ old($field) }}"></div>@endforeach
        <div class="field-group"><label for="next_service_date">Next service</label><input id="next_service_date" name="next_service_date" type="date" value="{{ old('next_service_date') }}"></div>
        @foreach(['problem_found'=>'Problem found','work_done'=>'Work done','parts_used_notes'=>'Parts used notes','notes'=>'Notes'] as $field=>$label)<div class="field-group"><label for="{{ $field }}">{{ $label }}</label><textarea id="{{ $field }}" name="{{ $field }}" @if($field==='work_done') required @endif>{{ old($field) }}</textarea>@error($field)<span class="error">{{ $message }}</span>@enderror</div>@endforeach<button>Save record</button>
    </form>
@endsection
