@extends('layouts.app')
@section('content')
    <header class="content-header"><div><p class="eyebrow">Livestock animals</p><h1>{{ $animal ? 'Edit animal' : 'New animal' }}</h1></div><a class="button secondary" href="{{ route('livestock.animals.index') }}">Back</a></header>
    <form class="form-panel" method="POST" action="{{ $animal ? route('livestock.animals.update',$animal) : route('livestock.animals.store') }}">@csrf @if($animal) @method('PUT') @endif
        <div class="field-group"><label for="organization_id">Organization</label><select id="organization_id" name="organization_id" required>@foreach($organizations as $organization)<option value="{{ $organization->id }}" @selected((string)old('organization_id',$animal?->organization_id)===(string)$organization->id)>{{ $organization->name }}</option>@endforeach</select>@error('organization_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="farm_id">Farm</label><select id="farm_id" name="farm_id" required>@foreach($farms as $farm)<option value="{{ $farm->id }}" @selected((string)old('farm_id',$animal?->farm_id)===(string)$farm->id)>{{ $farm->name }}</option>@endforeach</select>@error('farm_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="paddock_id">Paddock</label><select id="paddock_id" name="paddock_id"><option value="">None</option>@foreach($paddocks as $paddock)<option value="{{ $paddock->id }}" @selected((string)old('paddock_id',$animal?->paddock_id)===(string)$paddock->id)>{{ $paddock->name }}</option>@endforeach</select>@error('paddock_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="species_id">Species</label><select id="species_id" name="species_id" required>@foreach($species as $item)<option value="{{ $item->id }}" @selected((string)old('species_id',$animal?->species_id)===(string)$item->id)>{{ $item->name }}</option>@endforeach</select>@error('species_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="breed_id">Breed</label><select id="breed_id" name="breed_id"><option value="">None</option>@foreach($breeds as $breed)<option value="{{ $breed->id }}" @selected((string)old('breed_id',$animal?->breed_id)===(string)$breed->id)>{{ $breed->name }}</option>@endforeach</select>@error('breed_id')<span class="error">{{ $message }}</span>@enderror</div>
        @foreach(['animal_code'=>'Animal code','tag_number'=>'Tag number','rfid_number'=>'RFID number','name'=>'Name','weight_unit'=>'Weight unit','currency'=>'Currency'] as $field=>$label)<div class="field-group"><label for="{{ $field }}">{{ $label }}</label><input id="{{ $field }}" name="{{ $field }}" value="{{ old($field,$animal?->$field) }}" @if($field==='animal_code') required @endif>@error($field)<span class="error">{{ $message }}</span>@enderror</div>@endforeach
        <div class="field-group"><label for="sex">Sex</label><select id="sex" name="sex">@foreach(['female','male','unknown'] as $value)<option value="{{ $value }}" @selected(old('sex',$animal?->sex ?? 'unknown')===$value)>{{ ucfirst($value) }}</option>@endforeach</select></div>
        <div class="field-group"><label for="source">Source</label><select id="source" name="source">@foreach(['born_on_farm','purchased','transferred_in','donated','other'] as $value)<option value="{{ $value }}" @selected(old('source',$animal?->source ?? 'other')===$value)>{{ ucfirst(str_replace('_',' ',$value)) }}</option>@endforeach</select></div>
        <div class="field-group"><label for="status">Status</label><select id="status" name="status">@foreach(['active','sick','under_treatment','in_withdrawal','pregnant','lactating','sold','transferred_out','dead','culled','inactive','archived'] as $value)<option value="{{ $value }}" @selected(old('status',$animal?->status ?? 'active')===$value)>{{ ucfirst(str_replace('_',' ',$value)) }}</option>@endforeach</select></div>
        <div class="field-group"><label for="health_status">Health</label><select id="health_status" name="health_status"><option value="">Unknown</option>@foreach(['normal','watch','sick','critical','recovering','unknown'] as $value)<option value="{{ $value }}" @selected(old('health_status',$animal?->health_status)===$value)>{{ ucfirst($value) }}</option>@endforeach</select></div>
        <div class="field-group"><label for="production_status">Production</label><select id="production_status" name="production_status"><option value="">Unknown</option>@foreach(['growing','breeding','pregnant','lactating','dry','laying','finishing','retired','unknown'] as $value)<option value="{{ $value }}" @selected(old('production_status',$animal?->production_status)===$value)>{{ ucfirst($value) }}</option>@endforeach</select></div>
        @foreach(['date_of_birth'=>'Date of birth','acquisition_date'=>'Acquisition date'] as $field=>$label)<div class="field-group"><label for="{{ $field }}">{{ $label }}</label><input id="{{ $field }}" name="{{ $field }}" type="date" value="{{ old($field, optional($animal?->$field)->format('Y-m-d')) }}">@error($field)<span class="error">{{ $message }}</span>@enderror</div>@endforeach
        <div class="field-group"><label for="current_weight">Current weight</label><input id="current_weight" name="current_weight" type="number" step="0.01" min="0" value="{{ old('current_weight',$animal?->current_weight) }}"></div>
        <div class="field-group"><label for="acquisition_cost">Acquisition cost</label><input id="acquisition_cost" name="acquisition_cost" type="number" step="0.01" min="0" value="{{ old('acquisition_cost',$animal?->acquisition_cost) }}"></div>
        <div class="field-group"><label for="dam_id">Dam</label><select id="dam_id" name="dam_id"><option value="">None</option>@foreach($animals as $relative)<option value="{{ $relative->id }}" @selected((string)old('dam_id',$animal?->dam_id)===(string)$relative->id)>{{ $relative->animal_code }}</option>@endforeach</select></div>
        <div class="field-group"><label for="sire_id">Sire</label><select id="sire_id" name="sire_id"><option value="">None</option>@foreach($animals as $relative)<option value="{{ $relative->id }}" @selected((string)old('sire_id',$animal?->sire_id)===(string)$relative->id)>{{ $relative->animal_code }}</option>@endforeach</select></div>
        <div class="field-group"><label for="notes">Notes</label><textarea id="notes" name="notes">{{ old('notes',$animal?->notes) }}</textarea></div>
        <button type="submit">Save animal</button>
    </form>
@endsection
