@extends('layouts.app')
@section('content')
    <header class="content-header"><div><p class="eyebrow">{{ $animal->animal_code }}</p><h1>{{ $animal->name ?? $animal->animal_code }}</h1></div><div class="actions"><a class="button secondary" href="{{ route('livestock.animals.index') }}">Back</a><a class="button" href="{{ route('livestock.animals.edit',$animal) }}">Edit</a><form method="POST" action="{{ route('livestock.animals.deactivate',$animal) }}">@csrf<button>Deactivate</button></form></div></header>
    <dl class="detail-list"><div><dt>Species</dt><dd>{{ $animal->species?->name }}</dd></div><div><dt>Breed</dt><dd>{{ $animal->breed?->name ?? '-' }}</dd></div><div><dt>Farm</dt><dd>{{ $animal->farm?->name }}</dd></div><div><dt>Paddock</dt><dd>{{ $animal->paddock?->name ?? '-' }}</dd></div><div><dt>Status</dt><dd>{{ ucfirst($animal->status) }}</dd></div><div><dt>Health</dt><dd>{{ ucfirst($animal->health_status ?? 'unknown') }}</dd></div><div><dt>Production</dt><dd>{{ ucfirst($animal->production_status ?? 'unknown') }}</dd></div><div><dt>Weight</dt><dd>{{ $animal->current_weight ? $animal->current_weight.' '.$animal->weight_unit : '-' }}</dd></div><div><dt>Notes</dt><dd>{{ $animal->notes ?? '-' }}</dd></div></dl>
    <section class="summary-grid">
        <article class="summary-card"><span>Treatments</span><strong>{{ $animal->treatments->count() }}</strong></article><article class="summary-card"><span>Withdrawals</span><strong>{{ $animal->withdrawalPeriods->count() }}</strong></article><article class="summary-card"><span>Movements</span><strong>{{ $animal->movementRecords->count() }}</strong></article><article class="summary-card"><span>Yields</span><strong>{{ $animal->yieldRecords->count() }}</strong></article>
    </section>
    <div class="form-panel">
        <h2>Record treatment</h2><form method="POST" action="{{ route('livestock.animals.treatments.store',$animal) }}">@csrf <input type="hidden" name="treatment_type" value="treatment"><div class="field-group"><label>Treatment date</label><input name="treatment_date" type="date" required></div><div class="field-group"><label>Product</label><select name="product_id"><option value="">None</option>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->name }}</option>@endforeach</select></div><div class="field-group"><label>Reason</label><input name="condition_or_reason"></div><div class="field-group"><label>Meat withdrawal days</label><input name="withdrawal_meat_days" type="number" min="0"></div><div class="field-group"><label>Milk withdrawal days</label><input name="withdrawal_milk_days" type="number" min="0"></div><div class="field-group"><label>Egg withdrawal days</label><input name="withdrawal_egg_days" type="number" min="0"></div><button>Record treatment</button></form>
        <h2>Record movement</h2><form method="POST" action="{{ route('livestock.animals.movements.store',$animal) }}">@csrf <div class="field-group"><label>Movement date</label><input name="movement_date" type="date" required></div><div class="field-group"><label>To paddock</label><select name="to_paddock_id"><option value="">None</option>@foreach($paddocks as $paddock)<option value="{{ $paddock->id }}">{{ $paddock->name }}</option>@endforeach</select></div><div class="field-group"><label>Reason</label><input name="movement_reason"></div><button>Record movement</button></form>
        <h2>Record feed</h2><form method="POST" action="{{ route('livestock.animals.feed.store',$animal) }}">@csrf <div class="field-group"><label>Feed date</label><input name="feed_date" type="date" required></div><div class="field-group"><label>Quantity</label><input name="quantity" type="number" step="0.01" min="0.01" required></div><div class="field-group"><label>Unit</label><input name="quantity_unit" required></div><button>Record feed</button></form>
        <h2>Record weight</h2><form method="POST" action="{{ route('livestock.animals.weights.store',$animal) }}">@csrf <div class="field-group"><label>Weigh date</label><input name="weigh_date" type="date" required></div><div class="field-group"><label>Weight</label><input name="weight" type="number" step="0.01" min="0.01" required></div><div class="field-group"><label>Unit</label><input name="weight_unit" required></div><button>Record weight</button></form>
        <h2>Record breeding</h2><form method="POST" action="{{ route('livestock.animals.breeding.store',$animal) }}">@csrf <div class="field-group"><label>Breeding date</label><input name="breeding_date" type="date" required></div><div class="field-group"><label>Method</label><select name="breeding_method"><option value="natural">Natural</option><option value="artificial_insemination">Artificial insemination</option><option value="controlled_mating">Controlled mating</option><option value="unknown">Unknown</option><option value="other">Other</option></select></div><button>Record breeding</button></form>
        <h2>Record pregnancy check</h2><form method="POST" action="{{ route('livestock.animals.pregnancy-checks.store',$animal) }}">@csrf <div class="field-group"><label>Check date</label><input name="check_date" type="date" required></div><div class="field-group"><label>Result</label><select name="result"><option value="pregnant">Pregnant</option><option value="not_pregnant">Not pregnant</option><option value="uncertain">Uncertain</option><option value="recheck_needed">Recheck needed</option></select></div><button>Record pregnancy check</button></form>
        <h2>Record birth</h2><form method="POST" action="{{ route('livestock.animals.births.store',$animal) }}">@csrf <div class="field-group"><label>Birth date</label><input name="birth_date" type="date" required></div><div class="field-group"><label>Born</label><input name="number_born" type="number" min="0" required></div><div class="field-group"><label>Alive</label><input name="number_alive" type="number" min="0" required></div><div class="field-group"><label>Dead</label><input name="number_dead" type="number" min="0" required></div><button>Record birth</button></form>
        <h2>Record mortality</h2><form method="POST" action="{{ route('livestock.animals.mortality.store',$animal) }}">@csrf <div class="field-group"><label>Mortality date</label><input name="mortality_date" type="date" required></div><div class="field-group"><label>Cause</label><input name="cause"></div><button>Record mortality</button></form>
        <h2>Record yield</h2><form method="POST" action="{{ route('livestock.animals.yields.store',$animal) }}">@csrf <div class="field-group"><label>Yield date</label><input name="yield_date" type="date" required></div><div class="field-group"><label>Type</label><select name="yield_type"><option value="milk">Milk</option><option value="eggs">Eggs</option><option value="weight_gain">Weight gain</option><option value="honey">Honey</option><option value="fish">Fish</option><option value="wool">Wool</option><option value="manure">Manure</option><option value="other">Other</option></select></div><div class="field-group"><label>Quantity</label><input name="quantity" type="number" step="0.01" min="0.01" required></div><div class="field-group"><label>Unit</label><input name="unit_of_measure" required></div><button>Record yield</button></form>
    </div>
@endsection
