@extends('layouts.app')
@section('content')
    <header class="content-header"><div><p class="eyebrow">Asset usage</p><h1>Record usage</h1></div><a class="button secondary" href="{{ route('assets.usage.index') }}">Back</a></header>
    <form class="form-panel" method="POST" action="{{ route('assets.usage.store') }}">@csrf
        @include('assets::partials.scope-fields', ['record' => null])
        <div class="field-group"><label for="asset_id">Asset</label><select id="asset_id" name="asset_id" required>@foreach($assets as $asset)<option value="{{ $asset->id }}" @selected(old('asset_id')==$asset->id)>{{ $asset->asset_code }} - {{ $asset->name }}</option>@endforeach</select>@error('asset_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="usage_date">Date</label><input id="usage_date" name="usage_date" type="date" value="{{ old('usage_date', today()->toDateString()) }}" required></div>
        <div class="field-group"><label for="usage_type">Type</label><select id="usage_type" name="usage_type">@foreach(['general','crop_work','livestock_work','irrigation','transport','maintenance','storage','other'] as $value)<option value="{{ $value }}" @selected(old('usage_type','general')===$value)>{{ ucfirst(str_replace('_',' ',$value)) }}</option>@endforeach</select></div>
        @foreach(['related_task_id'=>$tasks,'related_irrigation_event_id'=>$events,'field_id'=>$fields,'paddock_id'=>$paddocks,'warehouse_id'=>$warehouses,'used_by_worker_id'=>$workers,'team_id'=>$teams] as $field=>$items)<div class="field-group"><label for="{{ $field }}">{{ ucfirst(str_replace('_id','',str_replace('_',' ',$field))) }}</label><select id="{{ $field }}" name="{{ $field }}"><option value="">None</option>@foreach($items as $item)<option value="{{ $item->id }}" @selected(old($field)==$item->id)>{{ $item->name ?? $item->task_number ?? $item->event_number }}</option>@endforeach</select>@error($field)<span class="error">{{ $message }}</span>@enderror</div>@endforeach
        <div class="field-group"><label for="used_by_user_id">Used by user</label><select id="used_by_user_id" name="used_by_user_id"><option value="">None</option>@foreach($memberships as $membership)<option value="{{ $membership->user_id }}" @selected(old('used_by_user_id')==$membership->user_id)>{{ $membership->user?->name }}</option>@endforeach</select>@error('used_by_user_id')<span class="error">{{ $message }}</span>@enderror</div>
        @foreach(['start_time'=>'Start time','end_time'=>'End time'] as $field=>$label)<div class="field-group"><label for="{{ $field }}">{{ $label }}</label><input id="{{ $field }}" name="{{ $field }}" type="time" value="{{ old($field) }}"></div>@endforeach
        @foreach(['duration_minutes'=>'Duration minutes','meter_start'=>'Meter start','meter_end'=>'Meter end','usage_quantity'=>'Usage quantity'] as $field=>$label)<div class="field-group"><label for="{{ $field }}">{{ $label }}</label><input id="{{ $field }}" name="{{ $field }}" type="number" step="0.01" min="0" value="{{ old($field) }}"></div>@endforeach
        <div class="field-group"><label for="usage_unit">Usage unit</label><input id="usage_unit" name="usage_unit" value="{{ old('usage_unit') }}"></div><div class="field-group"><label for="notes">Notes</label><textarea id="notes" name="notes">{{ old('notes') }}</textarea></div><button>Save usage</button>
    </form>
@endsection
