@extends('layouts.app')
@section('content')
    <header class="content-header"><div><p class="eyebrow">Maintenance schedule</p><h1>{{ $schedule ? 'Edit schedule' : 'New schedule' }}</h1></div><a class="button secondary" href="{{ route('assets.maintenance-schedules.index') }}">Back</a></header>
    <form class="form-panel" method="POST" action="{{ $schedule ? route('assets.maintenance-schedules.update',$schedule) : route('assets.maintenance-schedules.store') }}">@csrf @if($schedule) @method('PUT') @endif
        @include('assets::partials.scope-fields', ['record' => $schedule])
        <div class="field-group"><label for="asset_id">Asset</label><select id="asset_id" name="asset_id" required>@foreach($assets as $asset)<option value="{{ $asset->id }}" @selected(old('asset_id',$schedule?->asset_id)==$asset->id)>{{ $asset->asset_code }} - {{ $asset->name }}</option>@endforeach</select>@error('asset_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="maintenance_type">Type</label><select id="maintenance_type" name="maintenance_type">@foreach(['routine_service','inspection','repair','calibration','cleaning','lubrication','replacement','safety_check','other'] as $value)<option value="{{ $value }}" @selected(old('maintenance_type',$schedule?->maintenance_type ?? 'routine_service')===$value)>{{ ucfirst(str_replace('_',' ',$value)) }}</option>@endforeach</select></div>
        <div class="field-group"><label for="scheduled_date">Scheduled date</label><input id="scheduled_date" name="scheduled_date" type="date" value="{{ old('scheduled_date',$schedule?->scheduled_date?->toDateString()) }}" required></div>
        <div class="field-group"><label for="frequency_type">Frequency</label><select id="frequency_type" name="frequency_type"><option value="">None</option>@foreach(['none','daily','weekly','monthly','quarterly','annually','usage_based','custom'] as $value)<option value="{{ $value }}" @selected(old('frequency_type',$schedule?->frequency_type)===$value)>{{ ucfirst(str_replace('_',' ',$value)) }}</option>@endforeach</select></div>
        <div class="field-group"><label for="frequency_interval">Frequency interval</label><input id="frequency_interval" name="frequency_interval" type="number" min="1" value="{{ old('frequency_interval',$schedule?->frequency_interval) }}"></div>
        <div class="field-group"><label for="priority">Priority</label><select id="priority" name="priority">@foreach(['low','normal','high','urgent'] as $value)<option value="{{ $value }}" @selected(old('priority',$schedule?->priority ?? 'normal')===$value)>{{ ucfirst($value) }}</option>@endforeach</select></div>
        <div class="field-group"><label for="status">Status</label><select id="status" name="status">@foreach(['planned','assigned','in_progress','completed','missed','cancelled'] as $value)<option value="{{ $value }}" @selected(old('status',$schedule?->status ?? 'planned')===$value)>{{ ucfirst(str_replace('_',' ',$value)) }}</option>@endforeach</select></div>
        @foreach(['related_task_id'=>$tasks,'assigned_worker_id'=>$workers,'assigned_team_id'=>$teams] as $field=>$items)<div class="field-group"><label for="{{ $field }}">{{ ucfirst(str_replace('_id','',str_replace('_',' ',$field))) }}</label><select id="{{ $field }}" name="{{ $field }}"><option value="">None</option>@foreach($items as $item)<option value="{{ $item->id }}" @selected(old($field,$schedule?->$field)==$item->id)>{{ $item->name ?? $item->task_number }}</option>@endforeach</select>@error($field)<span class="error">{{ $message }}</span>@enderror</div>@endforeach
        <div class="field-group"><label for="assigned_user_id">Assigned user</label><select id="assigned_user_id" name="assigned_user_id"><option value="">None</option>@foreach($memberships as $membership)<option value="{{ $membership->user_id }}" @selected(old('assigned_user_id',$schedule?->assigned_user_id)==$membership->user_id)>{{ $membership->user?->name }}</option>@endforeach</select>@error('assigned_user_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="instructions">Instructions</label><textarea id="instructions" name="instructions">{{ old('instructions',$schedule?->instructions) }}</textarea></div><button>Save schedule</button>
    </form>
@endsection
