@extends('layouts.app')
@section('content')
    <header class="content-header"><div><p class="eyebrow">Irrigation event</p><h1>{{ $event ? 'Edit event' : 'Record event' }}</h1></div><a class="button secondary" href="{{ route('irrigation.events.index') }}">Back</a></header>
    <form class="form-panel" method="POST" action="{{ $event ? route('irrigation.events.update',$event) : route('irrigation.events.store') }}">@csrf @if($event) @method('PUT') @endif
        @include('irrigation::partials.scope-fields', ['record' => $event])
        @include('irrigation::partials.operational-selects', ['record' => $event, 'includeSource' => true])
        <div class="field-group"><label for="schedule_id">Schedule</label><select id="schedule_id" name="schedule_id"><option value="">None</option>@foreach($schedules as $schedule)<option value="{{ $schedule->id }}" @selected((string)old('schedule_id',$event?->schedule_id)===(string)$schedule->id)>{{ $schedule->schedule_number }}</option>@endforeach</select>@error('schedule_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="irrigation_date">Date</label><input id="irrigation_date" name="irrigation_date" type="date" value="{{ old('irrigation_date', optional($event?->irrigation_date)->format('Y-m-d')) }}" required></div>
        <div class="field-group"><label for="start_time">Start time</label><input id="start_time" name="start_time" type="time" value="{{ old('start_time',$event?->start_time) }}"></div>
        <div class="field-group"><label for="end_time">End time</label><input id="end_time" name="end_time" type="time" value="{{ old('end_time',$event?->end_time) }}"></div>
        <div class="field-group"><label for="duration_minutes">Duration minutes</label><input id="duration_minutes" name="duration_minutes" type="number" min="1" value="{{ old('duration_minutes',$event?->duration_minutes) }}"></div>
        <div class="field-group"><label for="water_volume">Water volume</label><input id="water_volume" name="water_volume" type="number" step="0.01" min="0" value="{{ old('water_volume',$event?->water_volume) }}"></div>
        <div class="field-group"><label for="water_volume_unit">Water volume unit</label><input id="water_volume_unit" name="water_volume_unit" value="{{ old('water_volume_unit',$event?->water_volume_unit) }}"></div>
        <div class="field-group"><label for="method">Method</label><select id="method" name="method"><option value="">None</option>@foreach(['drip','sprinkler','furrow','flood','manual','pivot','micro_sprinkler','other'] as $value)<option value="{{ $value }}" @selected(old('method',$event?->method)===$value)>{{ ucfirst(str_replace('_',' ',$value)) }}</option>@endforeach</select></div>
        <div class="field-group"><label for="status">Status</label><select id="status" name="status">@foreach(['recorded','approved','cancelled'] as $value)<option value="{{ $value }}" @selected(old('status',$event?->status ?? 'recorded')===$value)>{{ ucfirst($value) }}</option>@endforeach</select></div>
        <div class="field-group"><label for="performed_by_user_id">Performed by user</label><select id="performed_by_user_id" name="performed_by_user_id"><option value="">None</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected((string)old('performed_by_user_id',$event?->performed_by_user_id)===(string)$user->id)>{{ $user->name }}</option>@endforeach</select>@error('performed_by_user_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="performed_by_worker_id">Performed by worker</label><select id="performed_by_worker_id" name="performed_by_worker_id"><option value="">None</option>@foreach($workers as $worker)<option value="{{ $worker->id }}" @selected((string)old('performed_by_worker_id',$event?->performed_by_worker_id)===(string)$worker->id)>{{ $worker->name }}</option>@endforeach</select>@error('performed_by_worker_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="team_id">Team</label><select id="team_id" name="team_id"><option value="">None</option>@foreach($teams as $team)<option value="{{ $team->id }}" @selected((string)old('team_id',$event?->team_id)===(string)$team->id)>{{ $team->name }}</option>@endforeach</select>@error('team_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="notes">Notes</label><textarea id="notes" name="notes">{{ old('notes',$event?->notes) }}</textarea></div><button>Save event</button>
    </form>
@endsection
