@extends('layouts.app')
@section('content')
    <header class="content-header"><div><p class="eyebrow">Finance / Costing</p><h1>Finance dashboard</h1></div><div class="actions"><a class="button" href="{{ route('finance.cost-entries.create') }}">New cost entry</a><a class="button secondary" href="{{ route('finance.reports.summary') }}">Reports</a></div></header>
    <form class="filter-bar" method="GET"><input type="date" name="date_from" value="{{ $filters['date_from'] ?? '' }}"><input type="date" name="date_to" value="{{ $filters['date_to'] ?? '' }}"><select name="organization_id"><option value="">All organizations</option>@foreach($organizations as $organization)<option value="{{ $organization->id }}" @selected(($filters['organization_id'] ?? '') == $organization->id)>{{ $organization->name }}</option>@endforeach</select><select name="farm_id"><option value="">All farms</option>@foreach($farms as $farm)<option value="{{ $farm->id }}" @selected(($filters['farm_id'] ?? '') == $farm->id)>{{ $farm->name }}</option>@endforeach</select><button class="button secondary" type="submit">Filter</button></form>
    <section class="summary-grid"><article class="summary-card"><span>Confirmed costs</span><strong>{{ number_format($confirmedTotal, 2) }}</strong></article><article class="summary-card"><span>Draft costs</span><strong>{{ $draftCount }} / {{ number_format($draftTotal, 2) }}</strong></article><article class="summary-card"><span>Voided costs</span><strong>{{ $voidCount }} / {{ number_format($voidTotal, 2) }}</strong></article></section>
    <div class="actions"><a class="button secondary" href="{{ route('finance.categories.index') }}">Cost Categories</a><a class="button secondary" href="{{ route('finance.cost-centres.index') }}">Cost Centres</a><a class="button secondary" href="{{ route('finance.cost-entries.index') }}">Cost Entries</a><a class="button secondary" href="{{ route('finance.reports.categories') }}">Category Report</a><a class="button secondary" href="{{ route('finance.reports.allocations') }}">Allocation Report</a></div>
    <section class="grid-two"><article><h2>Costs by category</h2><table><thead><tr><th>Category</th><th>Total</th></tr></thead><tbody>@foreach($byCategory as $row)<tr><td>{{ $row->label }}</td><td>{{ number_format($row->total, 2) }}</td></tr>@endforeach</tbody></table></article><article><h2>Costs by source</h2><table><thead><tr><th>Source</th><th>Total</th></tr></thead><tbody>@foreach($bySource as $row)<tr><td>{{ str_replace('_',' ',$row->label) }}</td><td>{{ number_format($row->total, 2) }}</td></tr>@endforeach</tbody></table></article></section>
    <section class="grid-two"><article><h2>Costs by farm</h2><table><thead><tr><th>Farm</th><th>Total</th></tr></thead><tbody>@foreach($byFarm as $row)<tr><td>{{ $row->label }}</td><td>{{ number_format($row->total, 2) }}</td></tr>@endforeach</tbody></table></article><article><h2>Costs by month</h2><table><thead><tr><th>Month</th><th>Total</th></tr></thead><tbody>@foreach($byMonth as $row)<tr><td>{{ $row->label }}</td><td>{{ number_format($row->total, 2) }}</td></tr>@endforeach</tbody></table></article></section>
    <h2>Recent cost entries</h2><table><thead><tr><th>Date</th><th>Title</th><th>Category</th><th>Status</th><th>Amount</th><th>Action</th></tr></thead><tbody>@foreach($recentEntries as $entry)<tr><td>{{ $entry->entry_date?->toDateString() }}</td><td>{{ $entry->title }}</td><td>{{ $entry->category?->name }}</td><td>{{ $entry->status }}</td><td>{{ $entry->currency }} {{ number_format($entry->amount, 2) }}</td><td><a href="{{ route('finance.cost-entries.show', $entry) }}">View</a></td></tr>@endforeach</tbody></table>
@endsection
