@extends('layouts.app')
@section('content')
    <header class="content-header"><div><p class="eyebrow">Asset</p><h1>{{ $asset ? 'Edit asset' : 'New asset' }}</h1></div><a class="button secondary" href="{{ route('assets.items.index') }}">Back</a></header>
    <form class="form-panel" method="POST" action="{{ $asset ? route('assets.items.update',$asset) : route('assets.items.store') }}">@csrf @if($asset) @method('PUT') @endif
        @include('assets::partials.scope-fields', ['record' => $asset])
        <div class="field-group"><label for="category_id">Category</label><select id="category_id" name="category_id" required>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id',$asset?->category_id)==$category->id)>{{ $category->name }}</option>@endforeach</select>@error('category_id')<span class="error">{{ $message }}</span>@enderror</div>
        @foreach(['asset_code'=>'Asset code','name'=>'Name','serial_number'=>'Serial number','model'=>'Model','manufacturer'=>'Manufacturer','currency'=>'Currency'] as $field=>$label)<div class="field-group"><label for="{{ $field }}">{{ $label }}</label><input id="{{ $field }}" name="{{ $field }}" value="{{ old($field,$asset?->$field) }}" @if(in_array($field,['asset_code','name'])) required @endif>@error($field)<span class="error">{{ $message }}</span>@enderror</div>@endforeach
        <div class="field-group"><label for="asset_type">Type</label><select id="asset_type" name="asset_type">@foreach(['vehicle','tractor','machinery','pump','irrigation_equipment','tool','generator','storage_equipment','building','infrastructure','livestock_equipment','crop_equipment','general_equipment','other'] as $value)<option value="{{ $value }}" @selected(old('asset_type',$asset?->asset_type ?? 'general_equipment')===$value)>{{ ucfirst(str_replace('_',' ',$value)) }}</option>@endforeach</select></div>
        @foreach(['purchase_date'=>'Purchase date','warranty_expiry_date'=>'Warranty expiry','last_service_date'=>'Last service','next_service_date'=>'Next service'] as $field=>$label)<div class="field-group"><label for="{{ $field }}">{{ $label }}</label><input id="{{ $field }}" name="{{ $field }}" type="date" value="{{ old($field,$asset?->$field?->toDateString()) }}"></div>@endforeach
        @foreach(['purchase_cost'=>'Purchase cost','current_value'=>'Current value'] as $field=>$label)<div class="field-group"><label for="{{ $field }}">{{ $label }}</label><input id="{{ $field }}" name="{{ $field }}" type="number" step="0.01" min="0" value="{{ old($field,$asset?->$field) }}"></div>@endforeach
        @foreach(['site_id'=>$sites,'field_id'=>$fields,'paddock_id'=>$paddocks,'warehouse_id'=>$warehouses,'assigned_worker_id'=>$workers] as $field=>$items)<div class="field-group"><label for="{{ $field }}">{{ ucfirst(str_replace('_id','',str_replace('_',' ',$field))) }}</label><select id="{{ $field }}" name="{{ $field }}"><option value="">None</option>@foreach($items as $item)<option value="{{ $item->id }}" @selected(old($field,$asset?->$field)==$item->id)>{{ $item->name }}</option>@endforeach</select>@error($field)<span class="error">{{ $message }}</span>@enderror</div>@endforeach
        <div class="field-group"><label for="assigned_user_id">Assigned user</label><select id="assigned_user_id" name="assigned_user_id"><option value="">None</option>@foreach($memberships as $membership)<option value="{{ $membership->user_id }}" @selected(old('assigned_user_id',$asset?->assigned_user_id)==$membership->user_id)>{{ $membership->user?->name }}</option>@endforeach</select>@error('assigned_user_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="status">Status</label><select id="status" name="status">@foreach(['active','in_use','under_maintenance','broken_down','retired','sold','lost','inactive','archived'] as $value)<option value="{{ $value }}" @selected(old('status',$asset?->status ?? 'active')===$value)>{{ ucfirst(str_replace('_',' ',$value)) }}</option>@endforeach</select></div>
        <div class="field-group"><label for="condition_status">Condition</label><select id="condition_status" name="condition_status">@foreach(['excellent','good','fair','poor','critical','unknown'] as $value)<option value="{{ $value }}" @selected(old('condition_status',$asset?->condition_status ?? 'unknown')===$value)>{{ ucfirst($value) }}</option>@endforeach</select></div>
        <div class="field-group"><label for="acquisition_source">Acquisition source</label><select id="acquisition_source" name="acquisition_source"><option value="">None</option>@foreach(['purchased','leased','rented','donated','transferred_in','other'] as $value)<option value="{{ $value }}" @selected(old('acquisition_source',$asset?->acquisition_source)===$value)>{{ ucfirst(str_replace('_',' ',$value)) }}</option>@endforeach</select></div>
        <div class="field-group"><label for="description">Description</label><textarea id="description" name="description">{{ old('description',$asset?->description) }}</textarea></div><div class="field-group"><label for="notes">Notes</label><textarea id="notes" name="notes">{{ old('notes',$asset?->notes) }}</textarea></div><button>Save asset</button>
    </form>
@endsection
