@extends('layouts.app')
@section('content')
    <header class="content-header"><div><p class="eyebrow">Irrigation issue</p><h1>{{ $issue ? 'Edit issue' : 'New issue' }}</h1></div><a class="button secondary" href="{{ route('irrigation.issues.index') }}">Back</a></header>
    <form class="form-panel" method="POST" action="{{ $issue ? route('irrigation.issues.update',$issue) : route('irrigation.issues.store') }}">@csrf @if($issue) @method('PUT') @endif
        @include('irrigation::partials.scope-fields', ['record' => $issue])
        <div class="field-group"><label for="irrigation_zone_id">Zone</label><select id="irrigation_zone_id" name="irrigation_zone_id"><option value="">None</option>@foreach($zones as $zone)<option value="{{ $zone->id }}" @selected((string)old('irrigation_zone_id',$issue?->irrigation_zone_id)===(string)$zone->id)>{{ $zone->name }}</option>@endforeach</select>@error('irrigation_zone_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="water_source_id">Water source</label><select id="water_source_id" name="water_source_id"><option value="">None</option>@foreach($sources as $source)<option value="{{ $source->id }}" @selected((string)old('water_source_id',$issue?->water_source_id)===(string)$source->id)>{{ $source->name }}</option>@endforeach</select>@error('water_source_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="field_id">Field</label><select id="field_id" name="field_id"><option value="">None</option>@foreach($fields as $field)<option value="{{ $field->id }}" @selected((string)old('field_id',$issue?->field_id)===(string)$field->id)>{{ $field->name }}</option>@endforeach</select>@error('field_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="related_task_id">Related task</label><select id="related_task_id" name="related_task_id"><option value="">None</option>@foreach($tasks as $task)<option value="{{ $task->id }}" @selected((string)old('related_task_id',$issue?->related_task_id)===(string)$task->id)>{{ $task->title }}</option>@endforeach</select>@error('related_task_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="issue_date">Date</label><input id="issue_date" name="issue_date" type="date" value="{{ old('issue_date', optional($issue?->issue_date)->format('Y-m-d')) }}" required></div>
        <div class="field-group"><label for="issue_type">Type</label><select id="issue_type" name="issue_type">@foreach(['pump_failure','blocked_line','broken_pipe','low_pressure','water_shortage','over_irrigation','under_irrigation','leakage','power_failure','other'] as $value)<option value="{{ $value }}" @selected(old('issue_type',$issue?->issue_type ?? 'low_pressure')===$value)>{{ ucfirst(str_replace('_',' ',$value)) }}</option>@endforeach</select></div>
        <div class="field-group"><label for="severity">Severity</label><select id="severity" name="severity">@foreach(['low','medium','high','critical'] as $value)<option value="{{ $value }}" @selected(old('severity',$issue?->severity ?? 'medium')===$value)>{{ ucfirst($value) }}</option>@endforeach</select></div>
        <div class="field-group"><label for="status">Status</label><select id="status" name="status">@foreach(['open','in_progress','resolved','cancelled'] as $value)<option value="{{ $value }}" @selected(old('status',$issue?->status ?? 'open')===$value)>{{ ucfirst(str_replace('_',' ',$value)) }}</option>@endforeach</select></div>
        <div class="field-group"><label for="reported_by_worker_id">Reported by worker</label><select id="reported_by_worker_id" name="reported_by_worker_id"><option value="">None</option>@foreach($workers as $worker)<option value="{{ $worker->id }}" @selected((string)old('reported_by_worker_id',$issue?->reported_by_worker_id)===(string)$worker->id)>{{ $worker->name }}</option>@endforeach</select></div>
        <div class="field-group"><label for="description">Description</label><textarea id="description" name="description" required>{{ old('description',$issue?->description) }}</textarea></div><button>Save issue</button>
    </form>
@endsection
