@extends('layouts.MainLayout')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="d-flex justify-content-between align-items-center mb-4">
                <h1><i class="fas fa-chart-bar"></i> {{ $report->title }}</h1>
                <a href="{{ route('reports.index') }}" class="btn btn-secondary">
                    <i class="fas fa-arrow-left"></i> Back
                </a>
            </div>

            <div class="row">
                <div class="col-md-8">
                    <div class="card mb-4">
                        <div class="card-header">
                            <h5>Report Details</h5>
                        </div>
                        <div class="card-body">
                            <div class="row mb-3">
                                <div class="col-md-6">
                                    <strong>Report Type:</strong> {{ $report->report_type_name }}
                                </div>
                                <div class="col-md-6">
                                    <strong>Status:</strong>
                                    <span class="badge bg-{{ $report->status_color }}">{{ ucfirst($report->status) }}</span>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-md-6">
                                    <strong>Farm:</strong> {{ $report->farm->name ?? 'N/A' }}
                                </div>
                                <div class="col-md-6">
                                    <strong>Generated By:</strong> {{ $report->generatedBy->name ?? 'N/A' }}
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-md-6">
                                    <strong>Period:</strong> 
                                    {{ $report->report_period_start->format('M d, Y') }} - {{ $report->report_period_end->format('M d, Y') }}
                                </div>
                                <div class="col-md-6">
                                    <strong>Duration:</strong> {{ $report->days_in_period }} days
                                </div>
                            </div>
                            @if($report->description)
                            <div class="mt-3">
                                <strong>Description:</strong>
                                <p>{{ $report->description }}</p>
                            </div>
                            @endif
                        </div>
                    </div>

                    @if($report->status === 'completed' && $report->data)
                    <div class="card mb-4">
                        <div class="card-header">
                            <h5>Report Data</h5>
                        </div>
                        <div class="card-body">
                            <pre>{{ json_encode($report->data, JSON_PRETTY_PRINT) }}</pre>
                        </div>
                    </div>
                    @elseif($report->status === 'generating')
                    <div class="alert alert-info">
                        <i class="fas fa-spinner fa-spin"></i> Report is being generated. Please wait...
                    </div>
                    @elseif($report->status === 'failed')
                    <div class="alert alert-danger">
                        <i class="fas fa-exclamation-triangle"></i> Report generation failed. Please try again.
                    </div>
                    @endif
                </div>

                <div class="col-md-4">
                    <div class="card">
                        <div class="card-header">
                            <h5>Actions</h5>
                        </div>
                        <div class="card-body">
                            <div class="d-grid gap-2">
                                @if($report->status === 'completed')
                                    <a href="{{ route('reports.download', $report) }}" class="btn btn-success">
                                        <i class="fas fa-download"></i> Download Report
                                    </a>
                                @endif
                                <form action="{{ route('reports.destroy', $report) }}" method="POST" onsubmit="return confirm('Are you sure?');">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger w-100">
                                        <i class="fas fa-trash"></i> Delete Report
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
