@extends('layouts.app')
@section('content')
    <header class="content-header"><div><p class="eyebrow">Irrigation zone</p><h1>{{ $zone ? 'Edit zone' : 'New zone' }}</h1></div><a class="button secondary" href="{{ route('irrigation.zones.index') }}">Back</a></header>
    <form class="form-panel" method="POST" action="{{ $zone ? route('irrigation.zones.update',$zone) : route('irrigation.zones.store') }}">@csrf @if($zone) @method('PUT') @endif
        @include('irrigation::partials.scope-fields', ['record' => $zone])
        <div class="field-group"><label for="site_id">Site</label><select id="site_id" name="site_id"><option value="">None</option>@foreach($sites as $site)<option value="{{ $site->id }}" @selected((string)old('site_id',$zone?->site_id)===(string)$site->id)>{{ $site->name }}</option>@endforeach</select>@error('site_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="field_id">Field</label><select id="field_id" name="field_id"><option value="">None</option>@foreach($fields as $field)<option value="{{ $field->id }}" @selected((string)old('field_id',$zone?->field_id)===(string)$field->id)>{{ $field->name }}</option>@endforeach</select>@error('field_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="water_source_id">Water source</label><select id="water_source_id" name="water_source_id"><option value="">None</option>@foreach($sources as $source)<option value="{{ $source->id }}" @selected((string)old('water_source_id',$zone?->water_source_id)===(string)$source->id)>{{ $source->name }}</option>@endforeach</select>@error('water_source_id')<span class="error">{{ $message }}</span>@enderror</div>
        @foreach(['name'=>'Name','code'=>'Code','area_unit'=>'Area unit'] as $field=>$label)<div class="field-group"><label for="{{ $field }}">{{ $label }}</label><input id="{{ $field }}" name="{{ $field }}" value="{{ old($field,$zone?->$field) }}" @if(in_array($field,['name','code'])) required @endif>@error($field)<span class="error">{{ $message }}</span>@enderror</div>@endforeach
        <div class="field-group"><label for="zone_type">Type</label><select id="zone_type" name="zone_type">@foreach(['field_zone','greenhouse_zone','nursery_zone','orchard_zone','general_zone','other'] as $value)<option value="{{ $value }}" @selected(old('zone_type',$zone?->zone_type ?? 'field_zone')===$value)>{{ ucfirst(str_replace('_',' ',$value)) }}</option>@endforeach</select></div>
        <div class="field-group"><label for="irrigation_method">Method</label><select id="irrigation_method" name="irrigation_method">@foreach(['drip','sprinkler','furrow','flood','manual','pivot','micro_sprinkler','other'] as $value)<option value="{{ $value }}" @selected(old('irrigation_method',$zone?->irrigation_method ?? 'drip')===$value)>{{ ucfirst(str_replace('_',' ',$value)) }}</option>@endforeach</select></div>
        <div class="field-group"><label for="area">Area</label><input id="area" name="area" type="number" step="0.01" min="0" value="{{ old('area',$zone?->area) }}"></div>
        <div class="field-group"><label for="status">Status</label><select id="status" name="status">@foreach(['active','inactive','under_maintenance','archived'] as $value)<option value="{{ $value }}" @selected(old('status',$zone?->status ?? 'active')===$value)>{{ ucfirst(str_replace('_',' ',$value)) }}</option>@endforeach</select></div>
        <div class="field-group"><label for="notes">Notes</label><textarea id="notes" name="notes">{{ old('notes',$zone?->notes) }}</textarea></div><button>Save zone</button>
    </form>
@endsection
