@extends('layouts.app')
@section('content')
    <header class="content-header"><div><p class="eyebrow">Irrigation schedule</p><h1>{{ $schedule ? 'Edit schedule' : 'New schedule' }}</h1></div><a class="button secondary" href="{{ route('irrigation.schedules.index') }}">Back</a></header>
    <form class="form-panel" method="POST" action="{{ $schedule ? route('irrigation.schedules.update',$schedule) : route('irrigation.schedules.store') }}">@csrf @if($schedule) @method('PUT') @endif
        @include('irrigation::partials.scope-fields', ['record' => $schedule])
        @include('irrigation::partials.operational-selects', ['record' => $schedule, 'includeSource' => false])
        <div class="field-group"><label for="scheduled_date">Scheduled date</label><input id="scheduled_date" name="scheduled_date" type="date" value="{{ old('scheduled_date', optional($schedule?->scheduled_date)->format('Y-m-d')) }}" required>@error('scheduled_date')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="scheduled_start_time">Start time</label><input id="scheduled_start_time" name="scheduled_start_time" type="time" value="{{ old('scheduled_start_time',$schedule?->scheduled_start_time) }}"></div>
        <div class="field-group"><label for="scheduled_end_time">End time</label><input id="scheduled_end_time" name="scheduled_end_time" type="time" value="{{ old('scheduled_end_time',$schedule?->scheduled_end_time) }}"></div>
        <div class="field-group"><label for="planned_duration_minutes">Planned duration minutes</label><input id="planned_duration_minutes" name="planned_duration_minutes" type="number" min="1" value="{{ old('planned_duration_minutes',$schedule?->planned_duration_minutes) }}"></div>
        <div class="field-group"><label for="planned_water_volume">Planned water volume</label><input id="planned_water_volume" name="planned_water_volume" type="number" step="0.01" min="0" value="{{ old('planned_water_volume',$schedule?->planned_water_volume) }}"></div>
        <div class="field-group"><label for="water_volume_unit">Water volume unit</label><input id="water_volume_unit" name="water_volume_unit" value="{{ old('water_volume_unit',$schedule?->water_volume_unit) }}"></div>
        <div class="field-group"><label for="priority">Priority</label><select id="priority" name="priority">@foreach(['low','normal','high','urgent'] as $value)<option value="{{ $value }}" @selected(old('priority',$schedule?->priority ?? 'normal')===$value)>{{ ucfirst($value) }}</option>@endforeach</select></div>
        <div class="field-group"><label for="status">Status</label><select id="status" name="status">@foreach(['planned','assigned','in_progress','completed','missed','cancelled'] as $value)<option value="{{ $value }}" @selected(old('status',$schedule?->status ?? 'planned')===$value)>{{ ucfirst(str_replace('_',' ',$value)) }}</option>@endforeach</select></div>
        <div class="field-group"><label for="assigned_user_id">Assigned user</label><select id="assigned_user_id" name="assigned_user_id"><option value="">None</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected((string)old('assigned_user_id',$schedule?->assigned_user_id)===(string)$user->id)>{{ $user->name }}</option>@endforeach</select>@error('assigned_user_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="assigned_worker_id">Assigned worker</label><select id="assigned_worker_id" name="assigned_worker_id"><option value="">None</option>@foreach($workers as $worker)<option value="{{ $worker->id }}" @selected((string)old('assigned_worker_id',$schedule?->assigned_worker_id)===(string)$worker->id)>{{ $worker->name }}</option>@endforeach</select>@error('assigned_worker_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="assigned_team_id">Assigned team</label><select id="assigned_team_id" name="assigned_team_id"><option value="">None</option>@foreach($teams as $team)<option value="{{ $team->id }}" @selected((string)old('assigned_team_id',$schedule?->assigned_team_id)===(string)$team->id)>{{ $team->name }}</option>@endforeach</select>@error('assigned_team_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="instructions">Instructions</label><textarea id="instructions" name="instructions">{{ old('instructions',$schedule?->instructions) }}</textarea></div><button>Save schedule</button>
    </form>
@endsection
