@extends('layouts.app')
@section('content')
    <header class="content-header"><div><p class="eyebrow">Sales / Revenue</p><h1>{{ $record ? 'Edit' : 'New' }} sale</h1></div></header>
    @php $oldLines = old('lines', $record?->lines?->toArray() ?: [['description'=>'','unit'=>'kg','quantity'=>1,'unit_price'=>0],['description'=>'','unit'=>'kg','quantity'=>1,'unit_price'=>0],['description'=>'','unit'=>'kg','quantity'=>1,'unit_price'=>0]]); @endphp
    <form method="POST" action="{{ $record ? route('sales.records.update', $record) : route('sales.records.store') }}">@csrf @if($record) @method('PUT') @endif
        <div class="form-grid"><label>Organization<select name="organization_id" required>@foreach($organizations as $organization)<option value="{{ $organization->id }}" @selected(old('organization_id',$record?->organization_id)==$organization->id)>{{ $organization->name }}</option>@endforeach</select></label><label>Farm<select name="farm_id" required>@foreach($farms as $farm)<option value="{{ $farm->id }}" @selected(old('farm_id',$record?->farm_id)==$farm->id)>{{ $farm->name }}</option>@endforeach</select></label><label>Customer<select name="sales_customer_id"><option value="">Unspecified</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected(old('sales_customer_id',$record?->sales_customer_id)==$customer->id)>{{ $customer->name }}</option>@endforeach</select></label><label>Sale date<input name="sale_date" type="date" value="{{ old('sale_date',$record?->sale_date?->toDateString() ?? now()->toDateString()) }}" required></label><label>Channel<select name="channel"><option value="">Select</option>@foreach(['farm_gate','market','contract','delivery','cooperative','broker','other'] as $channel)<option value="{{ $channel }}" @selected(old('channel',$record?->channel)===$channel)>{{ $channel }}</option>@endforeach</select></label><label>Currency<input name="currency" maxlength="3" value="{{ old('currency',$record?->currency ?? 'KES') }}"></label><label>Discount<input name="discount_amount" type="number" step="0.01" min="0" value="{{ old('discount_amount',$record?->discount_amount ?? 0) }}"></label><label>Other charges<input name="other_charges_amount" type="number" step="0.01" min="0" value="{{ old('other_charges_amount',$record?->other_charges_amount ?? 0) }}"></label></div>
        <h2>Lines</h2><table><thead><tr><th>Item</th><th>Description</th><th>Category</th><th>Unit</th><th>Qty</th><th>Price</th><th>Discount</th><th>Operational link</th></tr></thead><tbody>@foreach($oldLines as $i => $line)<tr><td><select name="lines[{{ $i }}][sales_catalog_item_id]"><option value="">Free text</option>@foreach($items as $item)<option value="{{ $item->id }}" @selected(($line['sales_catalog_item_id'] ?? null)==$item->id)>{{ $item->name }}</option>@endforeach</select></td><td><input name="lines[{{ $i }}][description]" value="{{ $line['description'] ?? '' }}"></td><td><select name="lines[{{ $i }}][category]"><option value="">Select</option>@foreach(['crop_produce','livestock','animal_product','service','other'] as $category)<option value="{{ $category }}" @selected(($line['category'] ?? null)===$category)>{{ $category }}</option>@endforeach</select></td><td><input name="lines[{{ $i }}][unit]" value="{{ $line['unit'] ?? 'kg' }}"></td><td><input name="lines[{{ $i }}][quantity]" type="number" step="0.001" min="0" value="{{ $line['quantity'] ?? 1 }}"></td><td><input name="lines[{{ $i }}][unit_price]" type="number" step="0.01" min="0" value="{{ $line['unit_price'] ?? 0 }}"></td><td><input name="lines[{{ $i }}][discount_amount]" type="number" step="0.01" min="0" value="{{ $line['discount_amount'] ?? 0 }}"></td><td><select name="lines[{{ $i }}][crop_cycle_id]"><option value="">Crop cycle</option>@foreach($cropCycles as $cycle)<option value="{{ $cycle->id }}" @selected(($line['crop_cycle_id'] ?? null)==$cycle->id)>{{ $cycle->name }}</option>@endforeach</select><select name="lines[{{ $i }}][animal_id]"><option value="">Animal</option>@foreach($animals as $animal)<option value="{{ $animal->id }}" @selected(($line['animal_id'] ?? null)==$animal->id)>{{ $animal->animal_code }} {{ $animal->name }}</option>@endforeach</select><select name="lines[{{ $i }}][animal_group_id]"><option value="">Group</option>@foreach($animalGroups as $group)<option value="{{ $group->id }}" @selected(($line['animal_group_id'] ?? null)==$group->id)>{{ $group->name }}</option>@endforeach</select></td></tr>@endforeach</tbody></table>
        <label>Notes<textarea name="notes">{{ old('notes',$record?->notes) }}</textarea></label>@include('sales::partials.errors')<button class="button" type="submit">Save sale</button>
    </form>
@endsection
