@extends('layouts.app')
@section('content')
    <header class="content-header"><div><p class="eyebrow">Livestock groups</p><h1>{{ $group ? 'Edit group' : 'New group' }}</h1></div><a class="button secondary" href="{{ route('livestock.groups.index') }}">Back</a></header>
    <form class="form-panel" method="POST" action="{{ $group ? route('livestock.groups.update',$group) : route('livestock.groups.store') }}">@csrf @if($group) @method('PUT') @endif
        <div class="field-group"><label for="organization_id">Organization</label><select id="organization_id" name="organization_id" required>@foreach($organizations as $organization)<option value="{{ $organization->id }}" @selected((string)old('organization_id',$group?->organization_id)===(string)$organization->id)>{{ $organization->name }}</option>@endforeach</select>@error('organization_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="farm_id">Farm</label><select id="farm_id" name="farm_id" required>@foreach($farms as $farm)<option value="{{ $farm->id }}" @selected((string)old('farm_id',$group?->farm_id)===(string)$farm->id)>{{ $farm->name }}</option>@endforeach</select>@error('farm_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="paddock_id">Paddock</label><select id="paddock_id" name="paddock_id"><option value="">None</option>@foreach($paddocks as $paddock)<option value="{{ $paddock->id }}" @selected((string)old('paddock_id',$group?->paddock_id)===(string)$paddock->id)>{{ $paddock->name }}</option>@endforeach</select>@error('paddock_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="species_id">Species</label><select id="species_id" name="species_id" required>@foreach($species as $item)<option value="{{ $item->id }}" @selected((string)old('species_id',$group?->species_id)===(string)$item->id)>{{ $item->name }}</option>@endforeach</select>@error('species_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="breed_id">Breed</label><select id="breed_id" name="breed_id"><option value="">None</option>@foreach($breeds as $breed)<option value="{{ $breed->id }}" @selected((string)old('breed_id',$group?->breed_id)===(string)$breed->id)>{{ $breed->name }}</option>@endforeach</select>@error('breed_id')<span class="error">{{ $message }}</span>@enderror</div>
        @foreach(['group_code'=>'Group code','name'=>'Name','sex_composition'=>'Sex composition'] as $field=>$label)<div class="field-group"><label for="{{ $field }}">{{ $label }}</label><input id="{{ $field }}" name="{{ $field }}" value="{{ old($field,$group?->$field) }}" @if(in_array($field,['group_code','name'])) required @endif>@error($field)<span class="error">{{ $message }}</span>@enderror</div>@endforeach
        <div class="field-group"><label for="group_type">Group type</label><select id="group_type" name="group_type">@foreach(['flock','herd','batch','pond','pen_group','age_group','other'] as $value)<option value="{{ $value }}" @selected(old('group_type',$group?->group_type ?? 'other')===$value)>{{ ucfirst(str_replace('_',' ',$value)) }}</option>@endforeach</select></div>
        <div class="field-group"><label for="source">Source</label><select id="source" name="source">@foreach(['born_on_farm','purchased','transferred_in','donated','other'] as $value)<option value="{{ $value }}" @selected(old('source',$group?->source ?? 'other')===$value)>{{ ucfirst(str_replace('_',' ',$value)) }}</option>@endforeach</select></div>
        <div class="field-group"><label for="status">Status</label><select id="status" name="status">@foreach(['active','under_treatment','in_withdrawal','sold','transferred_out','closed','inactive','archived'] as $value)<option value="{{ $value }}" @selected(old('status',$group?->status ?? 'active')===$value)>{{ ucfirst(str_replace('_',' ',$value)) }}</option>@endforeach</select></div>
        @foreach(['initial_count'=>'Initial count','current_count'=>'Current count'] as $field=>$label)<div class="field-group"><label for="{{ $field }}">{{ $label }}</label><input id="{{ $field }}" name="{{ $field }}" type="number" min="0" value="{{ old($field,$group?->$field ?? 0) }}" required>@error($field)<span class="error">{{ $message }}</span>@enderror</div>@endforeach
        <div class="field-group"><label for="start_date">Start date</label><input id="start_date" name="start_date" type="date" value="{{ old('start_date', optional($group?->start_date)->format('Y-m-d')) }}"></div>
        <div class="field-group"><label for="health_status">Health</label><select id="health_status" name="health_status"><option value="">Unknown</option>@foreach(['normal','watch','sick','critical','recovering','unknown'] as $value)<option value="{{ $value }}" @selected(old('health_status',$group?->health_status)===$value)>{{ ucfirst($value) }}</option>@endforeach</select></div>
        <div class="field-group"><label for="production_status">Production</label><select id="production_status" name="production_status"><option value="">Unknown</option>@foreach(['growing','breeding','pregnant','lactating','dry','laying','finishing','retired','unknown'] as $value)<option value="{{ $value }}" @selected(old('production_status',$group?->production_status)===$value)>{{ ucfirst($value) }}</option>@endforeach</select></div>
        <div class="field-group"><label for="notes">Notes</label><textarea id="notes" name="notes">{{ old('notes',$group?->notes) }}</textarea></div>
        <button type="submit">Save group</button>
    </form>
@endsection
