@extends('layouts.app')
@section('content')
    <header class="content-header"><div><p class="eyebrow">Breakdown</p><h1>{{ $breakdown ? 'Edit breakdown' : 'Record breakdown' }}</h1></div><a class="button secondary" href="{{ route('assets.breakdowns.index') }}">Back</a></header>
    <form class="form-panel" method="POST" action="{{ $breakdown ? route('assets.breakdowns.update',$breakdown) : route('assets.breakdowns.store') }}">@csrf @if($breakdown) @method('PUT') @endif
        @include('assets::partials.scope-fields', ['record' => $breakdown])
        <div class="field-group"><label for="asset_id">Asset</label><select id="asset_id" name="asset_id" required>@foreach($assets as $asset)<option value="{{ $asset->id }}" @selected(old('asset_id',$breakdown?->asset_id)==$asset->id)>{{ $asset->asset_code }} - {{ $asset->name }}</option>@endforeach</select>@error('asset_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="related_task_id">Related task</label><select id="related_task_id" name="related_task_id"><option value="">None</option>@foreach($tasks as $task)<option value="{{ $task->id }}" @selected(old('related_task_id',$breakdown?->related_task_id)==$task->id)>{{ $task->task_number }}</option>@endforeach</select>@error('related_task_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="breakdown_date">Date</label><input id="breakdown_date" name="breakdown_date" type="date" value="{{ old('breakdown_date',$breakdown?->breakdown_date?->toDateString() ?? today()->toDateString()) }}" required></div>
        <div class="field-group"><label for="issue_type">Issue type</label><select id="issue_type" name="issue_type">@foreach(['mechanical_failure','electrical_failure','leakage','wear_and_tear','accident_damage','blocked_component','overheating','low_pressure','engine_issue','other'] as $value)<option value="{{ $value }}" @selected(old('issue_type',$breakdown?->issue_type ?? 'mechanical_failure')===$value)>{{ ucfirst(str_replace('_',' ',$value)) }}</option>@endforeach</select></div>
        <div class="field-group"><label for="severity">Severity</label><select id="severity" name="severity">@foreach(['low','medium','high','critical'] as $value)<option value="{{ $value }}" @selected(old('severity',$breakdown?->severity ?? 'medium')===$value)>{{ ucfirst($value) }}</option>@endforeach</select></div>
        <div class="field-group"><label for="status">Status</label><select id="status" name="status">@foreach(['open','in_progress','resolved','cancelled'] as $value)<option value="{{ $value }}" @selected(old('status',$breakdown?->status ?? 'open')===$value)>{{ ucfirst(str_replace('_',' ',$value)) }}</option>@endforeach</select></div>
        <div class="field-group"><label for="reported_by_worker_id">Reported by worker</label><select id="reported_by_worker_id" name="reported_by_worker_id"><option value="">None</option>@foreach($workers as $worker)<option value="{{ $worker->id }}" @selected(old('reported_by_worker_id',$breakdown?->reported_by_worker_id)==$worker->id)>{{ $worker->name }}</option>@endforeach</select>@error('reported_by_worker_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="reported_by_user_id">Reported by user</label><select id="reported_by_user_id" name="reported_by_user_id"><option value="">None</option>@foreach($memberships as $membership)<option value="{{ $membership->user_id }}" @selected(old('reported_by_user_id',$breakdown?->reported_by_user_id)==$membership->user_id)>{{ $membership->user?->name }}</option>@endforeach</select>@error('reported_by_user_id')<span class="error">{{ $message }}</span>@enderror</div>
        <div class="field-group"><label for="description">Description</label><textarea id="description" name="description" required>{{ old('description',$breakdown?->description) }}</textarea>@error('description')<span class="error">{{ $message }}</span>@enderror</div><button>Save breakdown</button>
    </form>
@endsection
